% =========================================================================
% Juan MS CV
% AGUILA - Propulsion Study 02
% Propeller diameter, blade count and pitch: what each costs in watts.
% =========================================================================
%
% WHAT THIS STUDY ANSWERS
%   1. How much motor power do I need for an 8 inch versus a 10 inch prop?
%   2. Two blades or three?
%   3. What pitch?
%
% WHAT IT DOES NOT DO
%   Pick a motor. That needs a thrust stand, because published thrust
%   figures are frequently optimistic and sometimes simply wrong.
%
% Aircraft: candidate B from Sizing Study 01.
%
% Run:  >> AguilaPropStudy02JMSCV
% =========================================================================

clear all; clc;

A = aguilaAssumptions();

% --- The aircraft this study is sizing propellers for --------------------
massKg          = 1.73;    % candidate B, with the calibrated hover efficiency
thrustToWeight  = 1.8;     % provisional, DR-10 not yet closed
nRotors         = 2;       % DECIDED
cruiseSpeed     = 17.1;    % m/s, from Study 01
liftToDrag      = 9.4;     % from Study 01

weightN      = massKg * A.g;
thrustHover  = weightN / nRotors;
thrustMax    = massKg * thrustToWeight * A.g / nRotors;
thrustCruise = (weightN / liftToDrag) / nRotors;

fprintf('=========================================================================\n');
fprintf(' AGUILA PROPULSION STUDY 02\n');
fprintf('=========================================================================\n');
fprintf(' Aircraft      %.2f kg, %d rotors, T/W %.1f\n', massKg, nRotors, thrustToWeight);
fprintf(' Per propeller HOVER  %6.2f N = %4.0f g\n', thrustHover, thrustHover/A.g*1000);
fprintf('               MAX    %6.2f N = %4.0f g\n', thrustMax,   thrustMax/A.g*1000);
fprintf('               CRUISE %6.2f N = %4.0f g   at %.1f m/s\n', ...
        thrustCruise, thrustCruise/A.g*1000, cruiseSpeed);
fprintf('\n');
fprintf(' Note the cruise number. It is only %.0f %% of the hover thrust. The same\n', ...
        thrustCruise/thrustHover*100);
fprintf(' propeller has to cover a %.0f:1 thrust range. Section 4 returns to this.\n', ...
        thrustHover/thrustCruise);

%% 1 -- Diameter: what does 8 inch cost against 10 inch? ------------------
fprintf('\n=========================================================================\n');
fprintf(' 1. DIAMETER\n');
fprintf('=========================================================================\n');
fprintf(' %6s %11s %10s %12s %13s %10s %10s\n', ...
        'prop', 'hover [W]', 'max [W]', 'hover [g/W]', 'disk [N/m^2]', 'RPM max', 'tip [m/s]');
diameters = [8 9 10 11];
for d = diameters
    Ph = aguilaPropModel(thrustHover, d, A);
    Pm = aguilaPropModel(thrustMax,   d, A);
    fprintf(' %5d" %11.0f %10.0f %12.1f %13.0f %10.0f %10.0f\n', ...
            d, Ph.powerW, Pm.powerW, Ph.efficiency, Ph.diskLoading, ...
            Pm.rpm, Pm.tipSpeed);
end
P8  = aguilaPropModel(thrustHover,  8, A);
P10 = aguilaPropModel(thrustHover, 10, A);
M8  = aguilaPropModel(thrustMax,    8, A);
M10 = aguilaPropModel(thrustMax,   10, A);
aguilaExplain('what this says', { ...
  sprintf('An 8 inch propeller costs %.0f %% more power than a 10 inch for exactly', ...
          (P8.powerW/P10.powerW - 1)*100), ...
  'the same thrust, in hover and at full power alike. That is not a small', ...
  'penalty, and there is no way to tune it away - it is geometry.', ...
  '', ...
  'The reason is in the momentum-theory equation: power scales with the', ...
  'square root of disk area. A 10 inch disk is 56 % larger than an 8 inch', ...
  'one, so it does the same job by moving more air more gently.', ...
  '', ...
  sprintf('Watch the RPM column too. To make %.0f g, an 8 inch propeller has to', ...
          thrustMax/A.g*1000), ...
  sprintf('turn %.0f RPM. That is racing-drone territory, and it is near the top', M8.rpm), ...
  'of what an 8 inch propeller will do at all.'});
aguilaExplain('motor rating you need', { ...
  sprintf(' 8 inch: %3.0f W per motor at full thrust -> specify at least %d W', ...
          M8.powerW,  ceil(M8.powerW/50)*50), ...
  sprintf('10 inch: %3.0f W per motor at full thrust -> specify at least %d W', ...
          M10.powerW, ceil(M10.powerW/50)*50), ...
  '', ...
  'In current, at the two battery voltages worth considering:', ...
  sprintf('   8 inch, 4S: %4.1f A burst, %4.1f A hover   |  6S: %4.1f A / %4.1f A', ...
          M8.powerW/14.8,  P8.powerW/14.8,  M8.powerW/22.2,  P8.powerW/22.2), ...
  sprintf('  10 inch, 4S: %4.1f A burst, %4.1f A hover   |  6S: %4.1f A / %4.1f A', ...
          M10.powerW/14.8, P10.powerW/14.8, M10.powerW/22.2, P10.powerW/22.2), ...
  '', ...
  'Approximate Kv, from the RPM each needs and allowing for load:', ...
  sprintf('   8 inch: %4.0f Kv on 4S,  %4.0f Kv on 6S', ...
          M8.rpm/(14.8*A.rpmUnderLoad),  M8.rpm/(22.2*A.rpmUnderLoad)), ...
  sprintf('  10 inch: %4.0f Kv on 4S,  %4.0f Kv on 6S', ...
          M10.rpm/(14.8*A.rpmUnderLoad), M10.rpm/(22.2*A.rpmUnderLoad))});

%% 2 -- Blade count -------------------------------------------------------
fprintf('\n=========================================================================\n');
fprintf(' 2. TWO BLADES OR THREE?\n');
fprintf('=========================================================================\n');
fprintf(' %22s %12s %12s %12s\n', '', '2-blade', '3-blade', 'change');
B2 = aguilaPropModel(thrustMax, 10, A, 2);
B3 = aguilaPropModel(thrustMax, 10, A, 3);
H2 = aguilaPropModel(thrustHover, 10, A, 2);
H3 = aguilaPropModel(thrustHover, 10, A, 3);
fprintf(' %22s %12.0f %12.0f %+11.0f%%\n', 'power at max [W]', ...
        B2.powerW, B3.powerW, (B3.powerW/B2.powerW-1)*100);
fprintf(' %22s %12.0f %12.0f %+11.0f%%\n', 'RPM at max thrust', ...
        B2.rpm, B3.rpm, (B3.rpm/B2.rpm-1)*100);
fprintf(' %22s %12.0f %12.0f %+11.0f%%\n', 'tip speed [m/s]', ...
        B2.tipSpeed, B3.tipSpeed, (B3.tipSpeed/B2.tipSpeed-1)*100);
fprintf(' %22s %12.1f %12.1f %+11.0f%%\n', 'hover efficiency [g/W]', ...
        H2.efficiency, H3.efficiency, (H3.efficiency/H2.efficiency-1)*100);
aguilaExplain('the surprise here', { ...
  'Momentum theory does not contain blade count at all. Only disk area.', ...
  'A three-blade propeller of the same diameter sweeps exactly the same', ...
  'disk, so its IDEAL power is identical.', ...
  '', ...
  'The whole difference is second-order: more blades means more blade area', ...
  'dragging through the air, so a slightly lower figure of merit. About 6 %.', ...
  '', ...
  'Nor does a third blade give 50 % more thrust - the blades interfere with', ...
  'each other, so the thrust coefficient rises by roughly 1.4x. The prop', ...
  'reaches the same thrust about 15 % slower, which is why three-blades are', ...
  'quieter and smoother.'});
aguilaExplain('when to choose three blades', { ...
  'Choose 3 blades when DIAMETER is the binding constraint - when geometry', ...
  'will not let you fit a bigger 2-blade. Then the extra blade buys thrust', ...
  'you could not otherwise have, and the 6 % is worth paying.', ...
  '', ...
  'Choose 3 blades if vibration is hurting you. Lower RPM and better balance', ...
  'matter on an airframe carrying an autopilot and a tilting wing.', ...
  '', ...
  'Otherwise choose 2 blades. Given free choice of diameter, a slightly', ...
  'larger 2-blade beats a 3-blade every time.', ...
  '', ...
  'NOT YET DECIDED: whether diameter is constrained. That comes out of the', ...
  'fuselage and landing-gear layout, which is not designed.'});

%% 3 -- Pitch -------------------------------------------------------------
fprintf('\n=========================================================================\n');
fprintf(' 3. PITCH\n');
fprintf('=========================================================================\n');
fprintf(' Cruise speed to be reached: %.1f m/s\n\n', cruiseSpeed);
fprintf(' %10s %8s %16s %20s %12s\n', ...
        'prop', 'P/D', 'max airspeed', 'reaches cruise?', 'hover [g/W]');
pitches = [3.5 4.5 5 6 7 8];
for p = pitches
    Pm = aguilaPropModel(thrustMax,   10, A, 2, p);
    Ph = aguilaPropModel(thrustHover, 10, A, 2, p);
    if Pm.maxAirspeed >= cruiseSpeed
        verdict = 'yes';
    else
        verdict = 'NO - cannot cruise';
    end
    fprintf(' %8s" %8.2f %13.1f m/s %20s %12.1f\n', ...
            sprintf('10x%.1f', p), Pm.pitchToDiam, Pm.maxAirspeed, verdict, Ph.efficiency);
end
aguilaExplain('what pitch is', { ...
  'Pitch is how far the propeller would screw itself forward in one turn if', ...
  'the air were solid. Air is not solid, so it slips - but pitch still sets', ...
  'a hard ceiling on how fast the propeller can push.', ...
  '', ...
  'Too little pitch and the aircraft physically cannot reach cruise speed:', ...
  'the blades run out of bite and start windmilling.', ...
  '', ...
  'Too much pitch and the blade sits at a steep angle when the aircraft is', ...
  'standing still, close to stalled, and hovers badly.'});
aguilaExplain('the window', { ...
  sprintf('Below 10x5 the propeller cannot reach %.1f m/s at all. That is not an', cruiseSpeed), ...
  'efficiency argument - the aircraft simply cannot fly the mission.', ...
  '', ...
  'Above 10x6 you start paying hover efficiency for top speed you have no', ...
  'use for.', ...
  '', ...
  '-> 10x5 to 10x6 is the usable window, and it is narrow. Verify it on the', ...
  '   thrust stand before ordering more than one pair.'});

%% 4 -- Why this is the hard part of a two-motor tilt-wing ----------------
fprintf('\n=========================================================================\n');
fprintf(' 4. THE UNDERLYING DIFFICULTY\n');
fprintf('=========================================================================\n');
fprintf(' %-28s %10s %10s\n', 'operating point', 'thrust [N]', 'speed [m/s]');
fprintf(' %-28s %10.2f %10.1f\n', 'hover',  thrustHover,  0.0);
fprintf(' %-28s %10.2f %10.1f\n', 'cruise', thrustCruise, cruiseSpeed);
aguilaExplain('what this means', { ...
  sprintf('One propeller, asked to cover a %.0f:1 thrust range from a standstill to', ...
          thrustHover/thrustCruise), ...
  sprintf('%.0f m/s. No fixed-pitch propeller is good at both ends of that.', cruiseSpeed), ...
  '', ...
  'A quadplane sidesteps this entirely: separate lift propellers and a', ...
  'separate cruise propeller, each optimised for one job. Your two', ...
  'propellers do both jobs, which is the price of the configuration.', ...
  '', ...
  'This is a known cost, not a new problem. It is why the pitch window in', ...
  'section 3 is so narrow, and why a variable-pitch or folding propeller is', ...
  'worth knowing about even though it is far too complex for Block 1.'});

%% 5 -- Charts ------------------------------------------------------------
% Chart 1: thrust against electrical power, 8 inch and 10 inch.
% Chart 2: hover efficiency in g/W against thrust, same two propellers.
% Chart 3: the pitch window.

thrustSweep = linspace(1, thrustMax*1.15, 120);
p8  = zeros(size(thrustSweep));  p10 = zeros(size(thrustSweep));
e8  = zeros(size(thrustSweep));  e10 = zeros(size(thrustSweep));
for i = 1:numel(thrustSweep)
    a = aguilaPropModel(thrustSweep(i),  8, A);
    b = aguilaPropModel(thrustSweep(i), 10, A);
    p8(i)  = a.powerW;   e8(i)  = a.efficiency;
    p10(i) = b.powerW;   e10(i) = b.efficiency;
end
grams = thrustSweep / A.g * 1000;

blue   = [0.165 0.471 0.839];    % validated categorical slot 1
orange = [0.922 0.408 0.204];    % validated categorical slot 2

figure('Name', 'Thrust against power', 'Color', 'w');
plot(grams, p8,  '-', 'Color', orange, 'LineWidth', 2); hold on;
plot(grams, p10, '-', 'Color', blue,   'LineWidth', 2);
plot(thrustHover/A.g*1000, P8.powerW,  'o', 'Color', orange, ...
     'MarkerFaceColor', orange, 'MarkerSize', 7);
plot(thrustHover/A.g*1000, P10.powerW, 'o', 'Color', blue, ...
     'MarkerFaceColor', blue,   'MarkerSize', 7);
xline_hover = thrustHover/A.g*1000;
plot([xline_hover xline_hover], [0 max(p8)], ':', 'Color', [0.5 0.5 0.5]);
plot([thrustMax/A.g*1000 thrustMax/A.g*1000], [0 max(p8)], ':', 'Color', [0.5 0.5 0.5]);
grid on; box off;
xlabel('thrust per propeller [g]'); ylabel('electrical power [W]');
title('Power needed for a given thrust');
legend({'8 inch', '10 inch'}, 'Location', 'northwest'); legend boxoff;
text(xline_hover, max(p8)*0.06, '  hover', 'FontSize', 9, 'Color', [0.4 0.4 0.4]);
text(thrustMax/A.g*1000, max(p8)*0.06, '  max', 'FontSize', 9, 'Color', [0.4 0.4 0.4]);
hold off;

figure('Name', 'Hover efficiency', 'Color', 'w');
plot(grams, e8,  '-', 'Color', orange, 'LineWidth', 2); hold on;
plot(grams, e10, '-', 'Color', blue,   'LineWidth', 2);
plot([xline_hover xline_hover], [0 max(e10)], ':', 'Color', [0.5 0.5 0.5]);
grid on; box off;
xlabel('thrust per propeller [g]'); ylabel('efficiency [g/W]');
title('How much thrust you get per watt');
legend({'8 inch', '10 inch'}, 'Location', 'northeast'); legend boxoff;
text(xline_hover, max(e10)*0.9, '  hover', 'FontSize', 9, 'Color', [0.4 0.4 0.4]);
hold off;

figure('Name', 'Pitch window', 'Color', 'w');
% Two stacked panels sharing one x-axis, NOT a dual y-axis chart. Two
% measures on two different scales forced onto one frame is the easiest way
% to make a chart that looks meaningful and is not - the reader cannot tell
% where the curves genuinely cross because the crossing depends entirely on
% how each axis happened to be scaled.
pitchSweep = linspace(3, 9, 60);
vmax = zeros(size(pitchSweep)); eff = zeros(size(pitchSweep));
for i = 1:numel(pitchSweep)
    a = aguilaPropModel(thrustMax,   10, A, 2, pitchSweep(i));
    b = aguilaPropModel(thrustHover, 10, A, 2, pitchSweep(i));
    vmax(i) = a.maxAirspeed;  eff(i) = b.efficiency;
end

subplot(2,1,1);
plot(pitchSweep, vmax, '-', 'Color', blue, 'LineWidth', 2); hold on;
plot(pitchSweep, cruiseSpeed*ones(size(pitchSweep)), '--', ...
     'Color', [0.45 0.45 0.45], 'LineWidth', 1);
grid on; box off;
ylabel('max airspeed [m/s]');
title('Pitch: too little cannot cruise, too much cannot hover');
text(3.15, cruiseSpeed*1.10, sprintf('cruise needs %.1f m/s', cruiseSpeed), ...
     'FontSize', 9, 'Color', [0.4 0.4 0.4]);
hold off;

subplot(2,1,2);
plot(pitchSweep, eff, '-', 'Color', orange, 'LineWidth', 2); hold on;
grid on; box off;
xlabel('propeller pitch [in], on a 10 inch propeller');
ylabel('hover efficiency [g/W]');
hold off;

fprintf('\n Three figures drawn. Chart 1 answers the question you asked;\n');
fprintf(' chart 2 is the same physics expressed the way people shop for motors;\n');
fprintf(' chart 3 shows the pitch window as two panels on a shared x-axis.\n');

fprintf('\n=========================================================================\n');
fprintf(' WHAT YOU CAN DECIDE FROM THIS\n');
fprintf('=========================================================================\n');
fprintf('   Propeller diameter   10 inch over 8 inch, on a %.0f %% power difference\n', ...
        (P8.powerW/P10.powerW - 1)*100);
fprintf('   Blade count          2, unless diameter turns out to be constrained\n');
fprintf('   Pitch window         10x5 to 10x6\n');
fprintf('   Motor rating         >= %d W per motor, %.0f A burst on 6S\n', ...
        ceil(M10.powerW/50)*50, M10.powerW/22.2);
fprintf('\n   STILL OPEN\n');
fprintf('     Exact motor        needs a thrust stand. Published figures are\n');
fprintf('                        routinely optimistic.\n');
fprintf('     Battery voltage    4S or 6S changes Kv, not power. Decide with the ESC.\n');
fprintf('     Diameter ceiling   set by fuselage and gear geometry, not yet designed.\n');
fprintf('=========================================================================\n\n');
