function aguilaReport(C, R, A, M)
% =========================================================================
% Juan MS CV
% AGUILA - Sizing Study 01
% Print the candidate comparison, with every column explained.
% =========================================================================

    fprintf('\n');
    fprintf('=========================================================================================\n');
    fprintf(' 1. THE FIVE CANDIDATES\n');
    fprintf('    Two rotors, design radius %.1f km, thrust-to-weight %.1f, disk loading %.0f N/m^2.\n', ...
            M.radius/1000, C(1).thrustToWeight, C(1).diskLoading);
    fprintf('=========================================================================================\n');
    for i = 1:numel(C)
        fprintf('   %-24s  %s\n', C(i).name, C(i).intent);
    end

    %% ---- Size and shape -------------------------------------------------
    fprintf('\n');
    fprintf(' SIZE AND SHAPE\n');
    fprintf(' ----------------------------------------------------------------------------------------\n');
    fprintf(' %-24s %8s %8s %8s %8s %7s %7s\n', ...
            'candidate', 'MTOW', 'span', 'chord', 'wing', 'aspect', 'print');
    fprintf(' %-24s %8s %8s %8s %8s %7s %7s\n', ...
            '', '[kg]', '[mm]', '[mm]', '[m^2]', 'ratio', 'segs');
    for i = 1:numel(R)
        fprintf(' %-24s %8.2f %8.0f %8.0f %8.3f %7.1f %7d\n', ...
                C(i).name, R(i).mass, R(i).span*1000, R(i).chord*1000, ...
                R(i).wingArea, C(i).aspectRatio, R(i).wingSegments);
    end
    aguilaExplain('what each column means', { ...
      'MTOW    Everything the aircraft weighs at takeoff, can included.', ...
      '        Lower is better: smaller motors, less energy, gentler crashes.', ...
      'span    Wingtip to wingtip. This is the number that decides whether it', ...
      '        fits in your car and how awkward it is to carry to a field.', ...
      'chord   Front-to-back width of the wing. Sets the Reynolds number', ...
      '        further down, and has to be wide enough to bury a can behind.', ...
      'wing    Total wing area. Everything else about the wing follows from', ...
      '        this plus the aspect ratio.', ...
      'print   How many pieces each half-wing splits into to fit the 256 mm', ...
      'segs    printer. Every joint is mass, work, and a place to fail.'});
    aguilaExplain('how to use this', { ...
      'A vs B vs C  -> same shape, shrinking wing. Watch MTOW go DOWN as the', ...
      '                wing gets smaller. A smaller wing is lighter, and a', ...
      '                faster aircraft spends less time in the air.', ...
      'B vs D vs E  -> same wing area, different shape. Area is identical, so', ...
      '                the only thing changing is how that area is arranged.', ...
      '                D is the shortest span you can get at this wing size.'});

    %% ---- Speed ----------------------------------------------------------
    fprintf('\n');
    fprintf(' SPEED AND AERODYNAMICS\n');
    fprintf(' ----------------------------------------------------------------------------------------\n');
    fprintf(' %-24s %9s %9s %8s %11s %9s\n', ...
            'candidate', 'stall', 'cruise', 'L/D', 'Reynolds', 'blown');
    fprintf(' %-24s %9s %9s %8s %11s %9s\n', ...
            '', '[m/s]', '[m/s]', '[-]', '[-]', '[%]');
    for i = 1:numel(R)
        fprintf(' %-24s %9.1f %9.1f %8.1f %11.0f %8.0f%%\n', ...
                C(i).name, R(i).vStall, R(i).vCruise, R(i).liftToDrag, ...
                R(i).reynolds, R(i).washedSpanFraction*100);
    end
    aguilaExplain('what each column means', { ...
      'stall     The slowest the wing can fly before it stops producing lift.', ...
      '          You never have to land at this speed - it takes off and lands', ...
      '          vertically - but it sets how fast everything else happens. A', ...
      '          high stall speed means a fast, twitchy aircraft that arrives', ...
      '          hard if a transition goes wrong.', ...
      'cruise    The speed it will actually fly the mission at, computed as the', ...
      '          minimum-drag speed (floored at 1.3x stall for safety).', ...
      'L/D       Lift divided by drag. How many metres forward per metre of', ...
      '          altitude lost with the motors off. Higher is more efficient.', ...
      'Reynolds  A measure of how "thick" the air feels to the wing. BELOW about', ...
      '          150,000 airfoils start behaving badly - laminar bubbles, poor', ...
      '          maximum lift, high drag. You want to stay above that.', ...
      'blown     The percentage of the wingspan sitting in propeller slipstream.', ...
      '          During the tilt transition, only the blown part of the wing', ...
      '          stays attached. The rest is stalled. Higher is safer.'});
    aguilaExplain('how to use this', { ...
      'This is where high wing loading starts costing you. C is the lightest', ...
      'aircraft in the table, but it is also the fastest - and speed on a first', ...
      'design is a real risk, not just a number.', ...
      '', ...
      'Ask yourself: how fast am I willing to have this thing arrive if a', ...
      'transition fails? That answer sets your wing loading ceiling, and it is', ...
      'a judgement call, not a calculation.'});

    %% ---- Power and energy -----------------------------------------------
    fprintf('\n');
    fprintf(' POWER, ENERGY AND PROPULSION\n');
    fprintf(' ----------------------------------------------------------------------------------------\n');
    fprintf(' %-24s %8s %8s %9s %9s %10s %9s\n', ...
            'candidate', 'hover', 'cruise', 'energy', 'battery', 'thrust/mot', 'flight');
    fprintf(' %-24s %8s %8s %9s %9s %10s %9s\n', ...
            '', '[W]', '[W]', '[Wh]', '[g]', '[kg]', '[min]');
    for i = 1:numel(R)
        fprintf(' %-24s %8.0f %8.0f %9.1f %9.0f %10.2f %9.1f\n', ...
                C(i).name, R(i).pHover, R(i).pCruise, R(i).energyWh, ...
                R(i).mass_battery*1000, R(i).thrustPerMotor, R(i).missionMinutes);
    end
    aguilaExplain('what each column means', { ...
      'hover       Electrical power to hold the aircraft still in the air.', ...
      '            Notice how much larger it is than cruise. Hovering is', ...
      '            expensive; that is the entire reason this has a wing.', ...
      'cruise      Electrical power in wing-borne flight.', ...
      'energy      Total for the whole mission, at the battery terminals.', ...
      'battery     Pack mass needed to deliver that energy, INCLUDING a 50%', ...
      '            reserve and only discharging to 80%. Not the pack you buy -', ...
      '            the minimum it must be.', ...
      'thrust/mot  Static thrust each of the two motors must produce. THIS IS', ...
      '            THE PROCUREMENT NUMBER. It decides what you can actually buy', ...
      '            and how much it costs.', ...
      'flight      How long the design mission takes, door to door.'});
    aguilaExplain('how to use this', { ...
      'thrust/mot is the column that turns into money. Roughly:', ...
      '   under 1.0 kg   2806-class, cheap, everywhere', ...
      '   1.0 - 1.8 kg   3110/4008-class, still easy to find', ...
      '   over 2.5 kg    5010-class and up, fewer options, more expensive', ...
      '', ...
      'If a candidate pushes you into a motor class you cannot source from a', ...
      'consumer retailer, that is a hard constraint (CR-02), not a preference.'});

    %% ---- Mass breakdown --------------------------------------------------
    fprintf('\n');
    fprintf(' WHERE THE MASS GOES [g]\n');
    fprintf(' ----------------------------------------------------------------------------------------\n');
    fprintf(' %-24s %7s %7s %7s %7s %8s %7s %8s %9s\n', ...
            'candidate', 'wing', 'tail', 'pivot', 'fuse', 'motors', 'batt', 'payload', 'payload');
    fprintf(' %-24s %7s %7s %7s %7s %8s %7s %8s %9s\n', ...
            '', '', '', '', '', '+ESC', '', '', 'fraction');
    for i = 1:numel(R)
        fprintf(' %-24s %7.0f %7.0f %7.0f %7.0f %8.0f %7.0f %8.0f %8.0f%%\n', ...
                C(i).name, R(i).mass_wing*1000, R(i).mass_tail*1000, ...
                R(i).mass_pivot*1000, R(i).mass_fuse*1000, ...
                (R(i).mass_motors + R(i).mass_esc)*1000, ...
                R(i).mass_battery*1000, R(i).mass_payload*1000, ...
                R(i).payloadFraction*100);
    end
    aguilaExplain('what to look at', { ...
      'payload fraction is the honest measure of how good the aircraft is.', ...
      'It is the share of takeoff weight that is actually useful load. Every', ...
      'other gram is overhead you are carrying to move the can.', ...
      '', ...
      'Notice the payload column never changes - the can is the can. What', ...
      'changes is everything you build around it. That is the whole game.'});
    fprintf('\n');
end
