#!/usr/bin/env python3
"""
Regenerate every published table and the home-page progress bar from aguila.py.

    python analysis/make_tables.py

Unknown values render as "not yet determined" rather than a plausible-looking
number. The site is allowed to be empty; it is not allowed to be wrong.

Juan Martinez - UAV AGUILA
"""

import os
import sys
from datetime import date

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import aguila as A  # noqa: E402

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "includes")
os.makedirs(OUT, exist_ok=True)

STAMP = (f'<!-- GENERATED by analysis/make_tables.py on {date.today()} '
         f'- do not edit by hand -->\n\n')

TBD = '<span class="tbd">not yet determined</span>'


def write(name, text):
    path = os.path.join(OUT, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(STAMP + text.rstrip() + "\n")
    print(f"  wrote {os.path.relpath(path)}")


def fmt(value, unit="", places=2):
    """Render a value, or the 'not yet determined' marker."""
    if value is None:
        return TBD
    if isinstance(value, float):
        return f"{value:,.{places}f}{unit}"
    if isinstance(value, int):
        return f"{value:,}{unit}"
    return f"{value}{unit}"


# ------------------------------------------------------------- progress bar
def progress_bar():
    done, total, pct = A.progress()
    # The rail spans from the centre of the first dot to the centre of the last, which is
    # inset by half a step at each end. Express the fill in that same coordinate space so it
    # terminates exactly on the last completed dot.
    span_pct = 100.0 * (total - 1) / total
    fill = 0.0 if done < 1 or total < 2 else (done - 1) / (total - 1) * span_pct
    fill = max(0.0, min(span_pct, fill))

    inset = 100.0 / total / 2
    h = [f'<div class="progress" markdown="0" style="--rail-inset:{inset:.4f}%">',
         '  <div class="progress-head">',
         f'    <span class="progress-count">{done} of {total} stages complete</span>',
         f'    <span class="progress-pct">{pct}%</span>',
         '  </div>',
         '  <div class="progress-track">',
         f'    <div class="progress-fill" style="width:{fill:.4f}%"></div>',
         '    <ol class="progress-steps">']
    for m in MILESTONE_ORDER():
        state = "done" if m["done"] else "todo"
        h.append(f'      <li class="step {state}">')
        h.append(f'        <span class="dot" aria-hidden="true"></span>')
        h.append(f'        <span class="step-label" title="{m["label"]}">'
                 f'{m.get("short", m["label"])}</span>')
        h.append('      </li>')
    h += ['    </ol>', '  </div>', '</div>']
    write("progress-bar.md", "\n".join(h))


def MILESTONE_ORDER():
    return A.MILESTONES


def milestone_table():
    t = "| Stage | Status | What it means |\n|---|---|---|\n"
    for m in A.MILESTONES:
        chip = ('<span class="chip done">Complete</span>' if m["done"]
                else '<span class="chip todo">Not started</span>')
        t += f'| **{m["label"]}** | {chip} | {m["note"]} |\n'
    write("milestones.md", t)


# ------------------------------------------------------------- what's decided
def decided_table():
    t = "| Aspect | Decision |\n|---|---|\n"
    for k, v in A.DECIDED.items():
        label = k.replace("_", " ").capitalize()
        t += f"| {label} | {v} |\n"
    write("decided.md", t)


# ------------------------------------------------------------- design point
def design_point():
    rows = [
        ("Maximum takeoff mass", A.PARAMS["MTOW"], " kg", 2),
        ("Wing area", A.PARAMS["S"], " m²", 2),
        ("Span", A.span(), " m", 2),
        ("Mean chord", A.chord(), " m", 3),
        ("Aspect ratio", A.PARAMS["AR"], "", 1),
        ("Wing loading", A.wing_loading(), " kg/m²", 1),
        ("Stall speed", A.stall_speed(), " m/s", 1),
        ("Cruise speed", A.PARAMS["V_cruise"], " m/s", 1),
        ("Chord Reynolds number", A.reynolds(), "", 0),
        ("Propeller diameter", A.PARAMS["prop_in"], " in", 0),
        ("Thrust required per motor", A.thrust_per_motor_g(), " g", 0),
        ("Hover power", A.hover_power(), " W", 0),
        ("Cruise power", A.cruise_power(), " W", 0),
        ("Battery", A.battery_Wh(), " Wh", 0),
        ("Endurance", A.endurance_min(), " min", 0),
        ("Still-air range", A.range_km(), " km", 1),
    ]
    t = "| Parameter | Value |\n|---|---|\n"
    for label, val, unit, places in rows:
        t += f"| {label} | {fmt(val, unit, places)} |\n"

    n_known = sum(1 for _, v, _, _ in rows if v is not None)
    t += (f'\n<p class="generated-note">{n_known} of {len(rows)} parameters determined. '
          f'Blank entries are genuinely undecided — nothing here is a placeholder value.</p>\n')
    write("design-point.md", t)


# ------------------------------------------------------------- mass budget
def mass_budget():
    if not A.MASS_ITEMS:
        t = ('!!! note "Mass budget is empty"\n'
             '    No component has been selected and no part has been made, so there is\n'
             '    nothing to weigh and nothing credible to estimate. Entries appear here as\n'
             '    components are chosen and as printed parts come off the bed.\n\n'
             'The known payload is the one fixed quantity:\n\n'
             '| Item | Mass |\n|---|---:|\n'
             f'| 33 cl can, filled | {fmt(A.PAYLOAD["can_full_g"], " g", 0)} |\n'
             f'| Release mechanism | {fmt(A.PAYLOAD["carrier_g"], " g", 0)} |\n')
    else:
        t = "| Item | Mass |\n|---|---:|\n"
        for k, v in A.MASS_ITEMS.items():
            t += f"| {k} | {v*1000:.0f} g |\n"
        total = A.mass_total()
        t += f"| **Total so far** | **{total*1000:.0f} g** |\n"
    write("mass-budget.md", t)


# -------------------------------------------------- transition, method only
def transition_envelope():
    """The unblown angle of attack needs no design decisions at all.

    Geometric AoA during transition equals the wing tilt angle, whatever the
    aircraft turns out to weigh. That is the part of the analysis that is
    already true, so it is the part that gets published.
    """
    t = ("| Wing tilt | Unblown wing AoA | Attached below 14°? |\n"
         "|---:|---:|---|\n")
    for tilt in (85, 70, 60, 45, 30, 20, 10, 5):
        state = "yes" if tilt < 14 else "**no — separated**"
        t += f"| {tilt}° | {tilt}° | {state} |\n"
    t += (f"\n<p class=\"generated-note\">Slipstream relief depends on rotor size and "
          f"aircraft mass, neither of which is decided. Current slipstream velocity: "
          f"{fmt(A.induced_velocity(), ' m/s', 1)}. Washed span fraction: "
          f"{fmt(A.washed_span_fraction(), '', 2)}.</p>\n")
    write("transition-envelope.md", t)


# ------------------------------------------------- control authority, method
def control_authority():
    c = A.yaw_couple_nacelle_tilt()
    t = ("| Quantity | Value |\n|---|---|\n"
         f"| Yaw couple from differential nacelle tilt | {fmt(c, ' N·m', 2)} |\n"
         f"| Estimated yaw inertia $I_{{zz}}$ | {fmt(A.yaw_inertia(), ' kg·m²', 3)} |\n"
         f"| Resulting angular acceleration | {fmt(A.yaw_accel_deg_s2(c), ' °/s²', 0)} |\n"
         f"| Requirement (DR-09) | {fmt(A.PARAMS['yaw_accel_min'], ' °/s²', 0)} |\n"
         f"| Nacelle differential travel | {fmt(A.PARAMS['tilt_diff_deg'], '°', 0)} |\n")
    t += ('\n<p class="generated-note">These depend on mass, span and rotor size. '
          'The <em>qualitative</em> finding below — that a rigid two-motor tilt-wing has '
          'no yaw effector at all — holds regardless of any of them.</p>\n')
    write("control-authority.md", t)


# ------------------------------------------------------------- open questions
def open_questions():
    q = [
        ("How big is the aircraft?",
         "Wing area, span and aspect ratio all follow from the mass budget, which follows "
         "from component selection. Nothing is sized yet.",
         "Preliminary sizing"),
        ("What does it weigh?",
         "Only the payload is known. Structure, propulsion and battery masses depend on "
         "decisions not yet taken.",
         "Preliminary sizing"),
        ("Which airfoil?",
         "Needs the operating Reynolds number, which needs the chord, which needs the sizing. "
         "The tilt-wing additionally demands a gentle stall.",
         "Aerodynamic design"),
        ("How does the wing pivot carry load?",
         "It must take full wing bending, rotate under load, hold position unpowered, and pass "
         "wiring across a moving joint. This gates the whole build.",
         "Structural design"),
        ("Which motors, propellers and battery?",
         "Deliberately deferred. Selecting hardware before the mass budget exists is how a "
         "design spirals.",
         "Components selected"),
        ("How much yaw authority does the nacelle differential actually give?",
         "The requirement for one is established. The magnitude depends on geometry that is "
         "not set, and must be measured on a thrust stand regardless.",
         "Components selected"),
    ]
    t = "| Question | Why it is still open | Answered at |\n|---|---|---|\n"
    for a, b, c in q:
        t += f"| **{a}** | {b} | {c} |\n"
    write("open-questions.md", t)


if __name__ == "__main__":
    print("Regenerating from analysis/aguila.py:")
    progress_bar()
    milestone_table()
    decided_table()
    design_point()
    mass_budget()
    transition_envelope()
    control_authority()
    open_questions()
    d, t, p = A.progress()
    print(f"Done. Progress: {d}/{t} stages ({p}%).")
